name: Jhoose Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_NO: 1.0.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Configure Source
      working-directory: ./src/Jhoose.Security
      run: dotnet nuget add source https://nuget.pkg.github.com/andrewmarkham/index.json --name "Github" --store-password-in-clear-text --username andrewmarkham --password ${{ secrets.PACKAGE_TOKEN }}

    - name: Use Node.js 14.4.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.4.0  

    - name: Run node
      working-directory: ./src/Jhoose.Security
      run: |
       npm install 
       npm run publish

    - name: Build
      working-directory: ./src/Jhoose.Security
      run: dotnet build --configuration Release -p:Version=${BUILD_NO}
      
    - name: Test
      working-directory: ./src
      run: dotnet test --no-build --verbosity normal
    
    - name: nuget push
      run: |
       dotnet nuget list source
       dotnet nuget push ./**/Jhoose.Security*.nupkg --source "Github" --skip-duplicate
